[project]
name = "test-openai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "getchar>=2.0.0",
    "openai-agents[voice]>=0.0.5",
    "sounddevice>=0.5.1",
    "textual>=2.1.2",
]
